# MACHINE LEARNING PROJECT


### Sales
- **ID_SALES**: ID sales department
- **Program_Code**: Program code of the trip
- **From_Grade**: Lowest grade in school of a participant
- **To_Grade**: Highest grade in school of a participant
- **Group_State**: School location
- **Days**: Number of days on the program
- **Travel_Type**: Travel mode (A = Air, B = Bus, T = Train)
- **Departure_Date**: Departure day
- **Return_Date**: Return day
- **Early_RPL**: First communication date inviting people to join
- **Latest_RPL**: Last communication inviting people to join
- **Cancelled_Pax**: Number of passengers who made a deposit but cancelled
- **Total_Discount_Pax**: Number of extra passengers (e.g. professors)
- **Initial_System_Date**: First date when trip was organized
- **SPR_Product_Type**: Aggregation of tour types
- **FPP**: Number of full-payment participant
- **Total_Pax**: Number of total passengers (including extra participants)
- **DepartureMonth**: Month of departure
- **GroupGradeTypeLow**: Lowest grade type in the trip
- **GroupGradeTypeHigh**: Highest grade type in the trip
- **GroupGradeType**: Combination of the above
- **MajorProgramCode**: Aggregation of program codes
- **FPP_to_School_enrollment**: The ratio of FPP to school enrollment
- **Retained**: target




### Finance
- **ID_FINANCE**: ID finance department
- **Deposit_Date**: Expected deposit day
- **Special_Pay**: Payment modality (internal code)
- **Tuition**: Price per full-payment participant (FPP)
- **FRP_Active**: Number of FPPs who bought trip-cancellation insurance
- **FRP_Cancelled**: Number of FPPs who bought trip-cancellation insurance and cancelled it
- **FRP_Take_up_percent_**: Percentage of FPPs who bought the insurance pay for it
- **EZ_Pay_Take_Up_Rate**: Percentage of FPPs use automatic bank draft
- **School_Sponsor**: Indication of whether or not the school is sponsoring the trip
- **SPR_Group_Revenue**: Amount paid for all of the participants
- **FPP_to_PAX**: Percentage of FPP
- **Num_of_Non_FPP_PAX**: Number of non-FPP participants


### CRM
- **ID_CRM**: ID CRM department
- **Poverty_Code**: Poverty code for the school area based on estimated percentage below the poverty line. A is 0 to 5.9, B is 6 to 15.9, C is 16 to 30.9, D is 31 or more, E is unclassified, Space if DISTCLASS = U (Supervisory Union)
- **Region**: State areas
- **CRM_Segment**: CRM code system (internal code)
- **School_Type**: Public or private
- **Parent_Meeting_Flag**: Indication whether a parent meeting was held
- **MDR_Low_Grade**: Lowest grade (not just participants) in the school
- **MDR_High_Grade**: Highest grade (not just participants) in the school
- **Total_School_Enrollment**: School enrollments
- **Income_Level**: Parent income level code. A is lowest, Q is highest, Z is unclassified
- **SPR_New_Existing**: New client indicator
- **NumberOfMeetingswithParents**: Number of meetings with parents prior to the trip
- **FirstMeeting**: The date of the first meeting with parents (NA if none held)
- **LastMeeting**: Date of the last meeting with parents (NA if none held)
- **DifferenceTraveltoFirstMeeting**: Days from the first parent meeting to travel date
- **DifferenceTraveltoLastMeeting**: Days from the last parent meeting to travel date
- **SchoolGradeTypeLow**: The lowest grade type in the school
- **SchoolGradeTypeHigh**: The highest grade type in the school
- **SchoolGradeType**: Combination of the above denoting the type of school
- **SchoolSizeIndicator**: Size of the school (S, M, L, S-M, M-L)

## Read CSV

In [45]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
# keep_default_na=False needed so that 'NA' is not converted to nan
finance_df = pd.read_csv("./data/train/finance_model.csv", keep_default_na=False)
sales_df = pd.read_csv("./data/train/sales_model.csv", keep_default_na=False)
crm_df = pd.read_csv("./data/train/crm_model.csv", keep_default_na=False)

print("Finance DF")
display(finance_df.head())

print("Sales DF")
display(sales_df.head())

print("CRM DF")
display(crm_df.head())

Finance DF

,ID_FINANCE,Deposit_Date,Special_Pay,Tuition,FRP_Active,FRP_Cancelled,FRP_Take_up_percent_,EZ_Pay_Take_Up_Rate,School_Sponsor,SPR_Group_Revenue,FPP_to_PAX,Num_of_Non_FPP_PAX
0,1389,11/08/2018,0,397,1,1,"0,020913435758935","0,017855577091883",1,447,"0,967035782753087",2
1,3090,01/06/2019,0,563,0,0,0,0,0,579,"0,993127324453424",1
2,3639,12/29/2018,0,617,0,0,0,0,0,529,"0,973945817054653",1
3,4249,11/05/2018,0,446,1,1,"0,019031830062446","0,019285349239465",1,381,"0,981972198095321",2
4,CP1021,10/20/2018,CP,582,15,11,"0,597236981275838","0,035036284101661",1,596,"0,963425740042094",2

Sales DF

,ID_SALES,Program_Code,From_Grade,To_Grade,Group_State,Days,Travel_Type,Departure_Date,Return_Date,Early_RPL,...,SPR_Product_Type,FPP,Total_Pax,DepartureMonth,GroupGradeTypeLow,GroupGradeTypeHigh,GroupGradeType,MajorProgramCode,FPP_to_School_enrollment,Retained
0,CC1387A,CC,10,10,CA,24,A,04/07/2019,05/01/2019,05/11/2018,...,East Coast,26,29,January,K,High,K->High,C,"0,126429354314411",1
1,CC139A,CC,5,6,CA,18,A,04/30/2019,05/18/2019,03/05/2018,...,East Coast,21,22,January,PK,Middle,PK->Middle,C,"0,173405156631824",0
2,CC1600A,CC,7,7,OR,13,A,03/17/2019,03/30/2019,,...,East Coast,7,7,January,K,Middle,K->Middle,C,"0,108985714542943",1
3,CC1701A,CC,8,8,CA,24,A,05/08/2019,06/01/2019,02/07/2018,...,East Coast,26,25,January,PK,Middle,PK->Middle,C,"0,142807017036153",1
4,CC1773A,CC,7,7,OR,13,A,03/17/2019,03/30/2019,,...,East Coast,7,7,January,K,Middle,K->Middle,C,"0,108985714542943",1

CRM DF

,ID_CRM,Poverty_Code,Region,CRM_Segment,School_Type,Parent_Meeting_Flag,MDR_Low_Grade,MDR_High_Grade,Total_School_Enrollment,Income_Level,SPR_New_Existing,NumberOfMeetingswithParents,FirstMeeting,LastMeeting,DifferenceTraveltoFirstMeeting,DifferenceTraveltoLastMeeting,SchoolGradeTypeLow,SchoolGradeTypeHigh,SchoolGradeType,SchoolSizeIndicator
0,01000I,0,Other,10,Catholic,1,PK,8,403,I,0,2,05/12/2018,09/19/2018,371,241,Middle,Middle,Middle->Middle,S-M
1,01001O,0,Other,9,CHD,1,K,12,732,O,0,1,09/05/2018,09/01/2018,150,154,Middle,Middle,Middle->Middle,M-L
2,01002G,0,Other,5,Catholic,1,K,8,521,G,1,1,09/09/2018,09/05/2018,259,263,Middle,Middle,Middle->Middle,S-M
3,01011Q,0,Other,9,CHD,1,K,12,437,Q,0,2,05/03/2018,09/04/2018,315,191,Middle,High,Middle->High,S-M
4,01013I,0,Dallas,1,CHD,1,PK,12,226,I,1,2,04/07/2018,08/08/2018,418,295,Middle,High,Middle->High,S

In [47]:
print(sales_df.shape)
print(finance_df.shape)
print(crm_df.shape)

(4153, 24)
(4151, 12)
(4148, 20)

In [48]:
print("Sales Columns:", sales_df.columns.tolist())
print("CRM Columns:", crm_df.columns.tolist())
print("Finance Columns:", finance_df.columns.tolist())

Sales Columns: ['ID_SALES', 'Program_Code', 'From_Grade', 'To_Grade', 'Group_State', 'Days', 'Travel_Type', 'Departure_Date', 'Return_Date', 'Early_RPL', 'Latest_RPL', 'Cancelled_Pax', 'Total_Discount_Pax', 'Initial_System_Date', 'SPR_Product_Type', 'FPP', 'Total_Pax', 'DepartureMonth', 'GroupGradeTypeLow', 'GroupGradeTypeHigh', 'GroupGradeType', 'MajorProgramCode', 'FPP_to_School_enrollment', 'Retained']
CRM Columns: ['ID_CRM', 'Poverty_Code', 'Region', 'CRM_Segment', 'School_Type', 'Parent_Meeting_Flag', 'MDR_Low_Grade', 'MDR_High_Grade', 'Total_School_Enrollment', 'Income_Level', 'SPR_New_Existing', 'NumberOfMeetingswithParents', 'FirstMeeting', 'LastMeeting', 'DifferenceTraveltoFirstMeeting', 'DifferenceTraveltoLastMeeting', 'SchoolGradeTypeLow', 'SchoolGradeTypeHigh', 'SchoolGradeType', 'SchoolSizeIndicator']
Finance Columns: ['ID_FINANCE', 'Deposit_Date', 'Special_Pay', 'Tuition', 'FRP_Active', 'FRP_Cancelled', 'FRP_Take_up_percent_', 'EZ_Pay_Take_Up_Rate', 'School_Sponsor', 'SPR_Group_Revenue', 'FPP_to_PAX', 'Num_of_Non_FPP_PAX']

Target Variable: Retained

In [49]:
retained_count = sales_df[sales_df['Retained'] == 1].shape[0]
total_sales = sales_df.shape[0]
print(total_sales)
print((retained_count * 100) / total_sales)

4153
60.72718516734891

## Create `ID_TRIP`

`ID_TRIP` is the ID that joins `finance_df` and `sales_df` in a one-to-one manner.

### Finance DF

In [ ]:
# Preliminary check
# Check unique values for `Special_Pay` (values used to build the ID) to see if they need special handling

print(f"Unique values for `Special_Pay`: {finance_df['Special_Pay'].unique()}")

Unique values for `Special_Pay`: ['0' 'CP' 'FR' 'NA' 'SA']

The only special value for `Special_Pay` is `0` which resolves to an empty string `''`.

Also `NA` can be considered a special value since when importing the CSV through pandas it resolves to `nan` which introduces a problem. We fix this by adding to the import `keep_default_na=False`.

In [51]:
# Creating `ID_TRIP`

def calc_id_trip_finance(row):
  special_pay = row["Special_Pay"] if row["Special_Pay"] != '0' else '' # Ternary check to resolve `0` to an empty string `''`
  ID = row["ID_FINANCE"]
  
  if ID.startswith(special_pay):
    return ID[len(special_pay):]
  else:
    raise ValueError(f"Error: Row ID '{row.name}' => '{ID}' does not start with '{special_pay}.'") # Throw error if not found, in that case ID calculation is wrong
  
finance_df["ID_TRIP"] = finance_df.apply(calc_id_trip_finance, axis=1)

display(finance_df.head())

,ID_FINANCE,Deposit_Date,Special_Pay,Tuition,FRP_Active,FRP_Cancelled,FRP_Take_up_percent_,EZ_Pay_Take_Up_Rate,School_Sponsor,SPR_Group_Revenue,FPP_to_PAX,Num_of_Non_FPP_PAX,ID_TRIP
0,1389,11/08/2018,0,397,1,1,"0,020913435758935","0,017855577091883",1,447,"0,967035782753087",2,1389
1,3090,01/06/2019,0,563,0,0,0,0,0,579,"0,993127324453424",1,3090
2,3639,12/29/2018,0,617,0,0,0,0,0,529,"0,973945817054653",1,3639
3,4249,11/05/2018,0,446,1,1,"0,019031830062446","0,019285349239465",1,381,"0,981972198095321",2,4249
4,CP1021,10/20/2018,CP,582,15,11,"0,597236981275838","0,035036284101661",1,596,"0,963425740042094",2,1021

### Sales DF

In [ ]:
# Preliminary check
# Check unique values for `Program_Code` and `Travel_Type` (values used to build the ID) to see if they need special handling

print(f"Unique values for `Program_Code`: {sales_df['Program_Code'].unique()}")
print(f"Unique values for `Travel_Type`: {sales_df['Travel_Type'].unique()}")

Unique values for `Program_Code`: ['CC' 'CD' 'CN' 'CVP' 'FN' 'HC' 'HD' 'HF' 'HG' 'HH' 'HIS' 'HN' 'HO' 'HP'
 'HS' 'HVP' 'HW' 'HX' 'HY' 'HZ' 'IC' 'IK' 'SC' 'SD' 'SG' 'SK' 'SM' 'ST']
Unique values for `Travel_Type`: ['A' 'T' 'B']

There is no value that requires any particular handling.

In [ ]:
# Creating `ID_TRIP`

def calc_id_trip_sales(row):
  program_code = row['Program_Code']
  travel_type = row['Travel_Type']
  ID = row['ID_SALES']
  
  if ID.startswith(program_code) and ID.endswith(travel_type):
    return ID[len(program_code):-len(travel_type)]
  else:
    # raise ValueError(f"Error: Row ID '{row.name}' => '{ID}' does not start with '{program_code}' AND/OR does not end with '{travel_type}'.") # Throw error if not found, in that case ID calculation is wrong
    print(f"Error: Row ID '{row.name}' => '{ID}' does not start with '{program_code}' AND/OR does not end with '{travel_type}'.") # Throw error if not found, in that case ID calculation is wrong
    # Looks like the 3 not matching because they don't end with a Travel_Type end with a '0'. This makes id 5 digits long which is the only case that happens, so we try and remove the 0.
    return ID[len(program_code):-1] 
  
sales_df["ID_TRIP"] = sales_df.apply(calc_id_trip_sales, axis=1)

display(sales_df.head())

Error: Row ID '852' => 'HD12110' does not start with 'HD' AND/OR does not end with 'A'.
Error: Row ID '1274' => 'HD20240' does not start with 'HD' AND/OR does not end with 'T'.
Error: Row ID '2122' => 'HD36320' does not start with 'HD' AND/OR does not end with 'T'.

,ID_SALES,Program_Code,From_Grade,To_Grade,Group_State,Days,Travel_Type,Departure_Date,Return_Date,Early_RPL,...,FPP,Total_Pax,DepartureMonth,GroupGradeTypeLow,GroupGradeTypeHigh,GroupGradeType,MajorProgramCode,FPP_to_School_enrollment,Retained,ID_TRIP
0,CC1387A,CC,10,10,CA,24,A,04/07/2019,05/01/2019,05/11/2018,...,26,29,January,K,High,K->High,C,"0,126429354314411",1,1387
1,CC139A,CC,5,6,CA,18,A,04/30/2019,05/18/2019,03/05/2018,...,21,22,January,PK,Middle,PK->Middle,C,"0,173405156631824",0,139
2,CC1600A,CC,7,7,OR,13,A,03/17/2019,03/30/2019,,...,7,7,January,K,Middle,K->Middle,C,"0,108985714542943",1,1600
3,CC1701A,CC,8,8,CA,24,A,05/08/2019,06/01/2019,02/07/2018,...,26,25,January,PK,Middle,PK->Middle,C,"0,142807017036153",1,1701
4,CC1773A,CC,7,7,OR,13,A,03/17/2019,03/30/2019,,...,7,7,January,K,Middle,K->Middle,C,"0,108985714542943",1,1773

### CRM DF

In [ ]:
# Preliminary check
# Check unique values for `Poverty_Code` and `Income_Level` (values used to build the ID) to see if they need special handling

print(f"Unique values for `Poverty_Code`: {crm_df['Poverty_Code'].unique()}")
print(f"Unique values for `Income_Level`: {crm_df['Income_Level'].unique()}")

Unique values for `Poverty_Code`: ['0' 'A' 'B' 'C' 'D' 'E']
Unique values for `Income_Level`: ['I' 'O' 'G' 'Q' '0' 'L' 'K' 'J' 'M' 'N' 'P' 'H' 'E' 'F' 'Z' 'A' 'C' 'D'
 'B' 'P5' 'P1' 'P4' 'P3']

There is no value that requires any particular handling.

In [55]:
# Creating `ID_TRIP`

def calc_id_trip_crm(row):
  poverty_code = row['Poverty_Code']
  income_level = row['Income_Level']
  ID = row['ID_CRM']
  
  if ID.startswith(poverty_code) and ID.endswith(income_level):
    return ID[len(poverty_code):-len(income_level)]
  else:
    raise ValueError(f"Error: Row ID '{row.name}' => '{ID}' does not start with '{poverty_code}' AND/OR does not end with '{income_level}'.") # Throw error if not found, in that case ID calculation is wrong
  
crm_df["ID_TRIP"] = crm_df.apply(calc_id_trip_crm, axis=1)

display(crm_df.head())

,ID_CRM,Poverty_Code,Region,CRM_Segment,School_Type,Parent_Meeting_Flag,MDR_Low_Grade,MDR_High_Grade,Total_School_Enrollment,Income_Level,...,NumberOfMeetingswithParents,FirstMeeting,LastMeeting,DifferenceTraveltoFirstMeeting,DifferenceTraveltoLastMeeting,SchoolGradeTypeLow,SchoolGradeTypeHigh,SchoolGradeType,SchoolSizeIndicator,ID_TRIP
0,01000I,0,Other,10,Catholic,1,PK,8,403,I,...,2,05/12/2018,09/19/2018,371,241,Middle,Middle,Middle->Middle,S-M,1000
1,01001O,0,Other,9,CHD,1,K,12,732,O,...,1,09/05/2018,09/01/2018,150,154,Middle,Middle,Middle->Middle,M-L,1001
2,01002G,0,Other,5,Catholic,1,K,8,521,G,...,1,09/09/2018,09/05/2018,259,263,Middle,Middle,Middle->Middle,S-M,1002
3,01011Q,0,Other,9,CHD,1,K,12,437,Q,...,2,05/03/2018,09/04/2018,315,191,Middle,High,Middle->High,S-M,1011
4,01013I,0,Dallas,1,CHD,1,PK,12,226,I,...,2,04/07/2018,08/08/2018,418,295,Middle,High,Middle->High,S,1013

In [56]:
# Check for duplicates to see if we have identified ID correctly

duplicates = finance_df['ID_TRIP'].value_counts()
duplicates = duplicates[duplicates > 1]  # Filter values that appear more than once

print(len(duplicates))

duplicates = sales_df['ID_TRIP'].value_counts()
duplicates = duplicates[duplicates > 1]  # Filter values that appear more than once

print(len(duplicates))

duplicates = crm_df['ID_TRIP'].value_counts()
duplicates = duplicates[duplicates > 1]  # Filter values that appear more than once

print(len(duplicates))

0
0
0

## Merge into `trips_df`

`trips_df` is a df containing all information regarding a trip: the actual trip data (gathered from `sales_df`) and the financial data (gathered from `financial_df`)

In [57]:
# Try merging with 'outer' so we see how many don't get matched

print("Merging Finance DF + Sales DF")

outer_finance_sales_df = finance_df.merge(sales_df, on="ID_TRIP", how="outer", indicator=True)

unmatched_rows = outer_finance_sales_df[outer_finance_sales_df["_merge"] != "both"]

print(f"Finance DF Lenght: {len(finance_df)}")
print(f"Sales DF Lenght: {len(sales_df)}")
print(f"Unmatched: {len(unmatched_rows)}")
display(unmatched_rows[["ID_FINANCE", "ID_SALES"]])

outer_finance_sales_df = outer_finance_sales_df.drop("_merge", axis=1)

# Now merge inner

inner_finance_sales_df = finance_df.merge(sales_df, on="ID_TRIP")

print(f"Merged DF Lenght: {len(inner_finance_sales_df)}")
display(inner_finance_sales_df)

# Try merging with 'outer' so we see how many don't get matched

print("Merging inance DF + Sales DF + CRM DF")

outer_finance_sales_crm_df = outer_finance_sales_df.merge(crm_df, on="ID_TRIP", how="outer", indicator=True)
unmatched_rows = outer_finance_sales_crm_df[outer_finance_sales_crm_df["_merge"] != "both"]

print(f"Finance DF Lenght: {len(finance_df)}")
print(f"Sales DF Lenght: {len(sales_df)}")
print(f"CRM DF Lenght: {len(crm_df)}")
print(f"Unmatched: {len(unmatched_rows)}")
display(unmatched_rows[["ID_FINANCE", "ID_SALES", "ID_CRM"]])

# Now merge inner

inner_finance_sales_crm_df = inner_finance_sales_df.merge(crm_df, on="ID_TRIP")

print(f"Merged DF Lenght: {len(inner_finance_sales_crm_df)}")
display(inner_finance_sales_crm_df)

Merging Finance DF + Sales DF
Finance DF Lenght: 4151
Sales DF Lenght: 4153
Unmatched: 8

     ID_FINANCE ID_SALES
419         NaN  HC1444A
474      SA1505      NaN
565         NaN  CC1600A
1184     NA2292      NaN
1751     NA2910      NaN
2579        NaN  SK3814A
3439        NaN  SK4757A
4105        NaN   SM946A

Merged DF Lenght: 4148

,ID_FINANCE,Deposit_Date,Special_Pay,Tuition,FRP_Active,FRP_Cancelled,FRP_Take_up_percent_,EZ_Pay_Take_Up_Rate,School_Sponsor,SPR_Group_Revenue,...,SPR_Product_Type,FPP,Total_Pax,DepartureMonth,GroupGradeTypeLow,GroupGradeTypeHigh,GroupGradeType,MajorProgramCode,FPP_to_School_enrollment,Retained
0,1389,11/08/2018,0,397,1,1,"0,020913435758935","0,017855577091883",1,447,...,CA History,42,56,January,PK,Elementary,PK->Elementary,H,"0,054841225784392",0
1,3090,01/06/2019,0,563,0,0,0,0,0,579,...,CA History,44,44,January,PK,Middle,PK->Middle,H,"0,03525993967086",0
2,3639,12/29/2018,0,617,0,0,0,0,0,529,...,CA History,48,48,January,PK,Middle,PK->Middle,H,"0,034835018104198",0
3,4249,11/05/2018,0,446,1,1,"0,019031830062446","0,019285349239465",1,381,...,CA History,45,50,January,PK,Elementary,PK->Elementary,H,"0,057255009368505",0
4,CP1021,10/20/2018,CP,582,15,11,"0,597236981275838","0,035036284101661",1,596,...,CA History,24,24,January,Elementary,Elementary,Elementary->Elementary,H,"0,052117332755443",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4143,SA886,10/04/2018,SA,402,0,0,0,0,1,378,...,CA History,33,34,January,PK,Middle,PK->Middle,H,"0,118074413043599",1
4144,SA888,05/30/2018,SA,670,0,0,0,0,0,734,...,East Coast,83,80,January,PK,High,PK->High,H,"0,087162826204532",1
4145,SA899,06/07/2018,SA,2151,0,0,0,0,0,2075,...,East Coast,14,15,January,Middle,High,Middle->High,H,"0,080513840536427",1
4146,SA939,10/14/2018,SA,414,0,0,0,0,1,418,...,CA History,33,39,January,PK,Middle,PK->Middle,H,"0,10213914597725",1
4147,SA959,10/22/2018,SA,1729,0,0,0,0,1,1830,...,East Coast,62,52,January,Middle,High,Middle->High,H,"0,107806938055631",1

Merging inance DF + Sales DF + CRM DF
Finance DF Lenght: 4151
Sales DF Lenght: 4153
CRM DF Lenght: 4148
Unmatched: 8

     ID_FINANCE ID_SALES ID_CRM
419         NaN  HC1444A    NaN
474      SA1505      NaN    NaN
565         NaN  CC1600A    NaN
1184     NA2292      NaN    NaN
1751     NA2910      NaN    NaN
2579        NaN  SK3814A    NaN
3439        NaN  SK4757A    NaN
4105        NaN   SM946A    NaN

Merged DF Lenght: 4148

,ID_FINANCE,Deposit_Date,Special_Pay,Tuition,FRP_Active,FRP_Cancelled,FRP_Take_up_percent_,EZ_Pay_Take_Up_Rate,School_Sponsor,SPR_Group_Revenue,...,SPR_New_Existing,NumberOfMeetingswithParents,FirstMeeting,LastMeeting,DifferenceTraveltoFirstMeeting,DifferenceTraveltoLastMeeting,SchoolGradeTypeLow,SchoolGradeTypeHigh,SchoolGradeType,SchoolSizeIndicator
0,1389,11/08/2018,0,397,1,1,"0,020913435758935","0,017855577091883",1,447,...,1,2,04/18/2018,08/31/2018,407,272,Elementary,Elementary,Elementary->Elementary,L
1,3090,01/06/2019,0,563,0,0,0,0,0,579,...,1,0,,,,,Elementary,Elementary,Elementary->Elementary,L
2,3639,12/29/2018,0,617,0,0,0,0,0,529,...,0,0,,,,,Elementary,Elementary,Elementary->Elementary,L
3,4249,11/05/2018,0,446,1,1,"0,019031830062446","0,019285349239465",1,381,...,0,2,04/29/2018,09/07/2018,398,267,Elementary,Elementary,Elementary->Elementary,L
4,CP1021,10/20/2018,CP,582,15,11,"0,597236981275838","0,035036284101661",1,596,...,0,0,,,,,Elementary,Elementary,Elementary->Elementary,S-M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4143,SA886,10/04/2018,SA,402,0,0,0,0,1,378,...,0,0,,,,,Elementary,Elementary,Elementary->Elementary,S
4144,SA888,05/30/2018,SA,670,0,0,0,0,0,734,...,1,0,,,,,Middle,Middle,Middle->Middle,L
4145,SA899,06/07/2018,SA,2151,0,0,0,0,0,2075,...,1,1,08/20/2018,08/24/2018,270,266,High,High,High->High,S
4146,SA939,10/14/2018,SA,414,0,0,0,0,1,418,...,0,1,09/05/2018,09/10/2018,256,251,Elementary,Elementary,Elementary->Elementary,S
4147,SA959,10/22/2018,SA,1729,0,0,0,0,1,1830,...,0,0,,,,,Middle,Middle,Middle->Middle,S-M

In [58]:
inner_finance_sales_crm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4148 entries, 0 to 4147
Data columns (total 57 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID_FINANCE                      4148 non-null   object
 1   Deposit_Date                    4148 non-null   object
 2   Special_Pay                     4148 non-null   object
 3   Tuition                         4148 non-null   int64
 4   FRP_Active                      4148 non-null   int64
 5   FRP_Cancelled                   4148 non-null   int64
 6   FRP_Take_up_percent_            4148 non-null   object
 7   EZ_Pay_Take_Up_Rate             4148 non-null   object
 8   School_Sponsor                  4148 non-null   int64
 9   SPR_Group_Revenue               4148 non-null   int64
 10  FPP_to_PAX                      4148 non-null   object
 11  Num_of_Non_FPP_PAX              4148 non-null   int64
 12  ID_TRIP                         4148 non-null   object
 13  ID_SALES                        4148 non-null   object
 14  Program_Code                    4148 non-null   object
 15  From_Grade                      4148 non-null   object
 16  To_Grade                        4148 non-null   object
 17  Group_State                     4148 non-null   object
 18  Days                            4148 non-null   int64
 19  Travel_Type                     4148 non-null   object
 20  Departure_Date                  4148 non-null   object
 21  Return_Date                     4148 non-null   object
 22  Early_RPL                       4148 non-null   object
 23  Latest_RPL                      4148 non-null   object
 24  Cancelled_Pax                   4148 non-null   int64
 25  Total_Discount_Pax              4148 non-null   int64
 26  Initial_System_Date             4148 non-null   object
 27  SPR_Product_Type                4148 non-null   object
 28  FPP                             4148 non-null   int64
 29  Total_Pax                       4148 non-null   int64
 30  DepartureMonth                  4148 non-null   object
 31  GroupGradeTypeLow               4148 non-null   object
 32  GroupGradeTypeHigh              4148 non-null   object
 33  GroupGradeType                  4148 non-null   object
 34  MajorProgramCode                4148 non-null   object
 35  FPP_to_School_enrollment        4148 non-null   object
 36  Retained                        4148 non-null   int64
 37  ID_CRM                          4148 non-null   object
 38  Poverty_Code                    4148 non-null   object
 39  Region                          4148 non-null   object
 40  CRM_Segment                     4148 non-null   object
 41  School_Type                     4148 non-null   object
 42  Parent_Meeting_Flag             4148 non-null   int64
 43  MDR_Low_Grade                   4148 non-null   object
 44  MDR_High_Grade                  4148 non-null   object
 45  Total_School_Enrollment         4148 non-null   int64
 46  Income_Level                    4148 non-null   object
 47  SPR_New_Existing                4148 non-null   int64
 48  NumberOfMeetingswithParents     4148 non-null   int64
 49  FirstMeeting                    4148 non-null   object
 50  LastMeeting                     4148 non-null   object
 51  DifferenceTraveltoFirstMeeting  4148 non-null   object
 52  DifferenceTraveltoLastMeeting   4148 non-null   object
 53  SchoolGradeTypeLow              4148 non-null   object
 54  SchoolGradeTypeHigh             4148 non-null   object
 55  SchoolGradeType                 4148 non-null   object
 56  SchoolSizeIndicator             4148 non-null   object
dtypes: int64(16), object(41)
memory usage: 1.8+ MB

In [59]:
df = inner_finance_sales_crm_df
df.head()

,ID_FINANCE,Deposit_Date,Special_Pay,Tuition,FRP_Active,FRP_Cancelled,FRP_Take_up_percent_,EZ_Pay_Take_Up_Rate,School_Sponsor,SPR_Group_Revenue,...,SPR_New_Existing,NumberOfMeetingswithParents,FirstMeeting,LastMeeting,DifferenceTraveltoFirstMeeting,DifferenceTraveltoLastMeeting,SchoolGradeTypeLow,SchoolGradeTypeHigh,SchoolGradeType,SchoolSizeIndicator
0,1389,11/08/2018,0,397,1,1,"0,020913435758935","0,017855577091883",1,447,...,1,2,04/18/2018,08/31/2018,407,272,Elementary,Elementary,Elementary->Elementary,L
1,3090,01/06/2019,0,563,0,0,0,0,0,579,...,1,0,,,,,Elementary,Elementary,Elementary->Elementary,L
2,3639,12/29/2018,0,617,0,0,0,0,0,529,...,0,0,,,,,Elementary,Elementary,Elementary->Elementary,L
3,4249,11/05/2018,0,446,1,1,"0,019031830062446","0,019285349239465",1,381,...,0,2,04/29/2018,09/07/2018,398,267,Elementary,Elementary,Elementary->Elementary,L
4,CP1021,10/20/2018,CP,582,15,11,"0,597236981275838","0,035036284101661",1,596,...,0,0,,,,,Elementary,Elementary,Elementary->Elementary,S-M

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4148 entries, 0 to 4147
Data columns (total 57 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID_FINANCE                      4148 non-null   object
 1   Deposit_Date                    4148 non-null   object
 2   Special_Pay                     4148 non-null   object
 3   Tuition                         4148 non-null   int64
 4   FRP_Active                      4148 non-null   int64
 5   FRP_Cancelled                   4148 non-null   int64
 6   FRP_Take_up_percent_            4148 non-null   object
 7   EZ_Pay_Take_Up_Rate             4148 non-null   object
 8   School_Sponsor                  4148 non-null   int64
 9   SPR_Group_Revenue               4148 non-null   int64
 10  FPP_to_PAX                      4148 non-null   object
 11  Num_of_Non_FPP_PAX              4148 non-null   int64
 12  ID_TRIP                         4148 non-null   object
 13  ID_SALES                        4148 non-null   object
 14  Program_Code                    4148 non-null   object
 15  From_Grade                      4148 non-null   object
 16  To_Grade                        4148 non-null   object
 17  Group_State                     4148 non-null   object
 18  Days                            4148 non-null   int64
 19  Travel_Type                     4148 non-null   object
 20  Departure_Date                  4148 non-null   object
 21  Return_Date                     4148 non-null   object
 22  Early_RPL                       4148 non-null   object
 23  Latest_RPL                      4148 non-null   object
 24  Cancelled_Pax                   4148 non-null   int64
 25  Total_Discount_Pax              4148 non-null   int64
 26  Initial_System_Date             4148 non-null   object
 27  SPR_Product_Type                4148 non-null   object
 28  FPP                             4148 non-null   int64
 29  Total_Pax                       4148 non-null   int64
 30  DepartureMonth                  4148 non-null   object
 31  GroupGradeTypeLow               4148 non-null   object
 32  GroupGradeTypeHigh              4148 non-null   object
 33  GroupGradeType                  4148 non-null   object
 34  MajorProgramCode                4148 non-null   object
 35  FPP_to_School_enrollment        4148 non-null   object
 36  Retained                        4148 non-null   int64
 37  ID_CRM                          4148 non-null   object
 38  Poverty_Code                    4148 non-null   object
 39  Region                          4148 non-null   object
 40  CRM_Segment                     4148 non-null   object
 41  School_Type                     4148 non-null   object
 42  Parent_Meeting_Flag             4148 non-null   int64
 43  MDR_Low_Grade                   4148 non-null   object
 44  MDR_High_Grade                  4148 non-null   object
 45  Total_School_Enrollment         4148 non-null   int64
 46  Income_Level                    4148 non-null   object
 47  SPR_New_Existing                4148 non-null   int64
 48  NumberOfMeetingswithParents     4148 non-null   int64
 49  FirstMeeting                    4148 non-null   object
 50  LastMeeting                     4148 non-null   object
 51  DifferenceTraveltoFirstMeeting  4148 non-null   object
 52  DifferenceTraveltoLastMeeting   4148 non-null   object
 53  SchoolGradeTypeLow              4148 non-null   object
 54  SchoolGradeTypeHigh             4148 non-null   object
 55  SchoolGradeType                 4148 non-null   object
 56  SchoolSizeIndicator             4148 non-null   object
dtypes: int64(16), object(41)
memory usage: 1.8+ MB

In [65]:
df.head()

,ID_FINANCE,Deposit_Date,Special_Pay,Tuition,FRP_Active,FRP_Cancelled,FRP_Take_up_percent_,EZ_Pay_Take_Up_Rate,School_Sponsor,SPR_Group_Revenue,...,SPR_New_Existing,NumberOfMeetingswithParents,FirstMeeting,LastMeeting,DifferenceTraveltoFirstMeeting,DifferenceTraveltoLastMeeting,SchoolGradeTypeLow,SchoolGradeTypeHigh,SchoolGradeType,SchoolSizeIndicator
0,1389,11/08/2018,0,397,1,1,"0,020913435758935","0,017855577091883",1,447,...,1,2,04/18/2018,08/31/2018,407,272,Elementary,Elementary,Elementary->Elementary,L
1,3090,01/06/2019,0,563,0,0,0,0,0,579,...,1,0,,,,,Elementary,Elementary,Elementary->Elementary,L
2,3639,12/29/2018,0,617,0,0,0,0,0,529,...,0,0,,,,,Elementary,Elementary,Elementary->Elementary,L
3,4249,11/05/2018,0,446,1,1,"0,019031830062446","0,019285349239465",1,381,...,0,2,04/29/2018,09/07/2018,398,267,Elementary,Elementary,Elementary->Elementary,L
4,CP1021,10/20/2018,CP,582,15,11,"0,597236981275838","0,035036284101661",1,596,...,0,0,,,,,Elementary,Elementary,Elementary->Elementary,S-M

In [66]:
import os
df.to_csv("./data/df_ML2.csv", index=False)