In [1126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [1127]:
# import data
df = pd.read_csv("./data/df_ML2.csv", keep_default_na=False)

In [1128]:
df.head()

,ID_FINANCE,Deposit_Date,Special_Pay,Tuition,FRP_Active,FRP_Cancelled,FRP_Take_up_percent_,EZ_Pay_Take_Up_Rate,School_Sponsor,SPR_Group_Revenue,...,SPR_New_Existing,NumberOfMeetingswithParents,FirstMeeting,LastMeeting,DifferenceTraveltoFirstMeeting,DifferenceTraveltoLastMeeting,SchoolGradeTypeLow,SchoolGradeTypeHigh,SchoolGradeType,SchoolSizeIndicator
0,1389,11/08/2018,0,397,1,1,"0,020913435758935","0,017855577091883",1,447,...,1,2,04/18/2018,08/31/2018,407,272,Elementary,Elementary,Elementary->Elementary,L
1,3090,01/06/2019,0,563,0,0,0,0,0,579,...,1,0,,,,,Elementary,Elementary,Elementary->Elementary,L
2,3639,12/29/2018,0,617,0,0,0,0,0,529,...,0,0,,,,,Elementary,Elementary,Elementary->Elementary,L
3,4249,11/05/2018,0,446,1,1,"0,019031830062446","0,019285349239465",1,381,...,0,2,04/29/2018,09/07/2018,398,267,Elementary,Elementary,Elementary->Elementary,L
4,CP1021,10/20/2018,CP,582,15,11,"0,597236981275838","0,035036284101661",1,596,...,0,0,,,,,Elementary,Elementary,Elementary->Elementary,S-M


### Sales
- **ID_SALES**: ID sales department
- **Program_Code**: Program code of the trip
- **From_Grade**: Lowest grade in school of a participant
- **To_Grade**: Highest grade in school of a participant
- **Group_State**: School location
- **Days**: Number of days on the program
- **Travel_Type**: Travel mode (A = Air, B = Bus, T = Train)
- **Departure_Date**: Departure day
- **Return_Date**: Return day
- **Early_RPL**: First communication date inviting people to join
- **Latest_RPL**: Last communication inviting people to join
- **Cancelled_Pax**: Number of passengers who made a deposit but cancelled
- **Total_Discount_Pax**: Number of extra passengers (e.g. professors)
- **Initial_System_Date**: First date when trip was organized
- **SPR_Product_Type**: Aggregation of tour types
- **FPP**: Number of full-payment participant
- **Total_Pax**: Number of total passengers (including extra participants)
- **DepartureMonth**: Month of departure
- **GroupGradeTypeLow**: Lowest grade type in the trip
- **GroupGradeTypeHigh**: Highest grade type in the trip
- **GroupGradeType**: Combination of the above
- **MajorProgramCode**: Aggregation of program codes
- **FPP_to_School_enrollment**: The ratio of FPP to school enrollment
- **Retained**: target




### Finance
- **ID_FINANCE**: ID finance department
- **Deposit_Date**: Expected deposit day
- **Special_Pay**: Payment modality (internal code)
- **Tuition**: Price per full-payment participant (FPP)
- **FRP_Active**: Number of FPPs who bought trip-cancellation insurance
- **FRP_Cancelled**: Number of FPPs who bought trip-cancellation insurance and cancelled it
- **FRP_Take_up_percent_**: Percentage of FPPs who bought the insurance pay for it
- **EZ_Pay_Take_Up_Rate**: Percentage of FPPs use automatic bank draft
- **School_Sponsor**: Indication of whether or not the school is sponsoring the trip
- **SPR_Group_Revenue**: Amount paid for all of the participants
- **FPP_to_PAX**: Percentage of FPP
- **Num_of_Non_FPP_PAX**: Number of non-FPP participants


### CRM
- **ID_CRM**: ID CRM department
- **Poverty_Code**: Poverty code for the school area based on estimated percentage below the poverty line. A is 0 to 5.9, B is 6 to 15.9, C is 16 to 30.9, D is 31 or more, E is unclassified, Space if DISTCLASS = U (Supervisory Union)
- **Region**: State areas
- **CRM_Segment**: CRM code system (internal code)
- **School_Type**: Public or private
- **Parent_Meeting_Flag**: Indication whether a parent meeting was held
- **MDR_Low_Grade**: Lowest grade (not just participants) in the school
- **MDR_High_Grade**: Highest grade (not just participants) in the school
- **Total_School_Enrollment**: School enrollments
- **Income_Level**: Parent income level code. A is lowest, Q is highest, Z is unclassified
- **SPR_New_Existing**: New client indicator
- **NumberOfMeetingswithParents**: Number of meetings with parents prior to the trip
- **FirstMeeting**: The date of the first meeting with parents (NA if none held)
- **LastMeeting**: Date of the last meeting with parents (NA if none held)
- **DifferenceTraveltoFirstMeeting**: Days from the first parent meeting to travel date
- **DifferenceTraveltoLastMeeting**: Days from the last parent meeting to travel date
- **SchoolGradeTypeLow**: The lowest grade type in the school
- **SchoolGradeTypeHigh**: The highest grade type in the school
- **SchoolGradeType**: Combination of the above denoting the type of school
- **SchoolSizeIndicator**: Size of the school (S, M, L, S-M, M-L)

In [1129]:
# Visialize data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4148 entries, 0 to 4147
Data columns (total 57 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID_FINANCE                      4148 non-null   object
 1   Deposit_Date                    4148 non-null   object
 2   Special_Pay                     4148 non-null   object
 3   Tuition                         4148 non-null   int64
 4   FRP_Active                      4148 non-null   int64
 5   FRP_Cancelled                   4148 non-null   int64
 6   FRP_Take_up_percent_            4148 non-null   object
 7   EZ_Pay_Take_Up_Rate             4148 non-null   object
 8   School_Sponsor                  4148 non-null   int64
 9   SPR_Group_Revenue               4148 non-null   int64
 10  FPP_to_PAX                      4148 non-null   object
 11  Num_of_Non_FPP_PAX              4148 non-null   int64
 12  ID_TRIP                         4148 non-null   int64
 13  ID_SALES                        4148 non-null   object
 14  Program_Code                    4148 non-null   object
 15  From_Grade                      4148 non-null   object
 16  To_Grade                        4148 non-null   object
 17  Group_State                     4148 non-null   object
 18  Days                            4148 non-null   int64
 19  Travel_Type                     4148 non-null   object
 20  Departure_Date                  4148 non-null   object
 21  Return_Date                     4148 non-null   object
 22  Early_RPL                       4148 non-null   object
 23  Latest_RPL                      4148 non-null   object
 24  Cancelled_Pax                   4148 non-null   int64
 25  Total_Discount_Pax              4148 non-null   int64
 26  Initial_System_Date             4148 non-null   object
 27  SPR_Product_Type                4148 non-null   object
 28  FPP                             4148 non-null   int64
 29  Total_Pax                       4148 non-null   int64
 30  DepartureMonth                  4148 non-null   object
 31  GroupGradeTypeLow               4148 non-null   object
 32  GroupGradeTypeHigh              4148 non-null   object
 33  GroupGradeType                  4148 non-null   object
 34  MajorProgramCode                4148 non-null   object
 35  FPP_to_School_enrollment        4148 non-null   object
 36  Retained                        4148 non-null   int64
 37  ID_CRM                          4148 non-null   object
 38  Poverty_Code                    4148 non-null   object
 39  Region                          4148 non-null   object
 40  CRM_Segment                     4148 non-null   object
 41  School_Type                     4148 non-null   object
 42  Parent_Meeting_Flag             4148 non-null   int64
 43  MDR_Low_Grade                   4148 non-null   object
 44  MDR_High_Grade                  4148 non-null   object
 45  Total_School_Enrollment         4148 non-null   int64
 46  Income_Level                    4148 non-null   object
 47  SPR_New_Existing                4148 non-null   int64
 48  NumberOfMeetingswithParents     4148 non-null   int64
 49  FirstMeeting                    4148 non-null   object
 50  LastMeeting                     4148 non-null   object
 51  DifferenceTraveltoFirstMeeting  4148 non-null   object
 52  DifferenceTraveltoLastMeeting   4148 non-null   object
 53  SchoolGradeTypeLow              4148 non-null   object
 54  SchoolGradeTypeHigh             4148 non-null   object
 55  SchoolGradeType                 4148 non-null   object
 56  SchoolSizeIndicator             4148 non-null   object
dtypes: int64(17), object(40)
memory usage: 1.8+ MB

In [1130]:
df.shape

(4148, 57)

# Missing values

## Empty strings

In [1131]:
empty_counts = (df == '').sum()

result = pd.DataFrame({'Empty Strings': empty_counts})
print(result)

                                Empty Strings
ID_FINANCE                                  0
Deposit_Date                                0
Special_Pay                                 0
Tuition                                     0
FRP_Active                                  0
FRP_Cancelled                               0
FRP_Take_up_percent_                        0
EZ_Pay_Take_Up_Rate                         0
School_Sponsor                              0
SPR_Group_Revenue                           0
FPP_to_PAX                                  0
Num_of_Non_FPP_PAX                          0
ID_TRIP                                     0
ID_SALES                                    0
Program_Code                                0
From_Grade                                226
To_Grade                                  269
Group_State                                 0
Days                                        0
Travel_Type                                 0
Departure_Date                              0
Return_Date                                 0
Early_RPL                                1167
Latest_RPL                                 36
Cancelled_Pax                               0
Total_Discount_Pax                          0
Initial_System_Date                        16
SPR_Product_Type                            0
FPP                                         0
Total_Pax                                   0
DepartureMonth                              0
GroupGradeTypeLow                           0
GroupGradeTypeHigh                          0
GroupGradeType                              0
MajorProgramCode                            0
FPP_to_School_enrollment                  159
Retained                                    0
ID_CRM                                      0
Poverty_Code                                0
Region                                      0
CRM_Segment                                 4
School_Type                                 0
Parent_Meeting_Flag                         0
MDR_Low_Grade                               0
MDR_High_Grade                              0
Total_School_Enrollment                     0
Income_Level                                0
SPR_New_Existing                            0
NumberOfMeetingswithParents                 0
FirstMeeting                              596
LastMeeting                               596
DifferenceTraveltoFirstMeeting            596
DifferenceTraveltoLastMeeting             596
SchoolGradeTypeLow                          0
SchoolGradeTypeHigh                         0
SchoolGradeType                             0
SchoolSizeIndicator                       159

## Zeros (numeric columns)

In [1132]:
# Select numeric columns
numeric_cols = df.select_dtypes(include=['number'])

# Identify strictly binary columns (contain only 0 and 1)
binary_cols = [col for col in numeric_cols.columns if set(numeric_cols[col].dropna().unique()).issubset({0, 1})]

# Exclude strictly binary columns
non_binary_cols = numeric_cols.drop(columns=binary_cols)

# Count zeros in the remaining numeric columns
zero_counts = (non_binary_cols == 0).sum()

print(zero_counts)

Tuition                          0
FRP_Active                     221
FRP_Cancelled                  822
SPR_Group_Revenue                0
Num_of_Non_FPP_PAX              27
ID_TRIP                          0
Days                             0
Cancelled_Pax                  417
Total_Discount_Pax              27
FPP                              0
Total_Pax                        0
Total_School_Enrollment        159
NumberOfMeetingswithParents    596
dtype: int64

## Null values

In [1133]:
df.isnull().sum()

ID_FINANCE                        0
Deposit_Date                      0
Special_Pay                       0
Tuition                           0
FRP_Active                        0
FRP_Cancelled                     0
FRP_Take_up_percent_              0
EZ_Pay_Take_Up_Rate               0
School_Sponsor                    0
SPR_Group_Revenue                 0
FPP_to_PAX                        0
Num_of_Non_FPP_PAX                0
ID_TRIP                           0
ID_SALES                          0
Program_Code                      0
From_Grade                        0
To_Grade                          0
Group_State                       0
Days                              0
Travel_Type                       0
Departure_Date                    0
Return_Date                       0
Early_RPL                         0
Latest_RPL                        0
Cancelled_Pax                     0
Total_Discount_Pax                0
Initial_System_Date               0
SPR_Product_Type                  0
FPP                               0
Total_Pax                         0
DepartureMonth                    0
GroupGradeTypeLow                 0
GroupGradeTypeHigh                0
GroupGradeType                    0
MajorProgramCode                  0
FPP_to_School_enrollment          0
Retained                          0
ID_CRM                            0
Poverty_Code                      0
Region                            0
CRM_Segment                       0
School_Type                       0
Parent_Meeting_Flag               0
MDR_Low_Grade                     0
MDR_High_Grade                    0
Total_School_Enrollment           0
Income_Level                      0
SPR_New_Existing                  0
NumberOfMeetingswithParents       0
FirstMeeting                      0
LastMeeting                       0
DifferenceTraveltoFirstMeeting    0
DifferenceTraveltoLastMeeting     0
SchoolGradeTypeLow                0
SchoolGradeTypeHigh               0
SchoolGradeType                   0
SchoolSizeIndicator               0
dtype: int64

# Fixing columns

## Grades

In [1134]:
df['GroupGradeTypeHigh'].value_counts(dropna=False)

GroupGradeTypeHigh
Middle        3106
High           731
Elementary     195
Undefined      116
Name: count, dtype: int64

In [1135]:
df['GroupGradeTypeLow'].value_counts(dropna=False)

GroupGradeTypeLow
Middle        2158
K              756
PK             694
Elementary     239
High           185
Undefined      116
Name: count, dtype: int64

In [1136]:
df['MDR_Low_Grade'].value_counts(dropna=False)

MDR_Low_Grade
6     1521
K      756
PK     694
7      610
9      180
5      169
0      116
4       29
8       27
3       23
1       14
10       5
2        4
Name: count, dtype: int64

In [1137]:
df['MDR_High_Grade'].value_counts(dropna=False)

MDR_High_Grade
8     2872
12     626
6      190
5      176
NA     116
9       94
7       44
4       11
11       6
10       5
1        4
3        2
2        2
Name: count, dtype: int64

In [1138]:
df['SchoolGradeTypeLow'].value_counts(dropna=False)

SchoolGradeTypeLow
Middle        3214
Elementary     464
High           244
Undefined      226
Name: count, dtype: int64

In [1139]:
df['SchoolGradeTypeHigh'].value_counts(dropna=False)

SchoolGradeTypeHigh
Middle        3060
High           463
Elementary     356
Undefined      269
Name: count, dtype: int64

New Mappings:

In [1140]:
df['GroupGradeTypeHigh'] = df['GroupGradeTypeHigh'].replace({'PK': 1, 'K': 2, 'Elementary': 3, 'Middle': 4, 'High': 5, 'Undefined': 0, 'NA': 0}).astype(int)
df['GroupGradeTypeLow'] = df['GroupGradeTypeLow'].replace({'PK': 1, 'K': 2, 'Elementary': 3, 'Middle': 4, 'High': 5, 'Undefined': 0, 'NA': 0}).astype(int)
df['MDR_Low_Grade'] = df['MDR_Low_Grade'].replace({'PK': 1, 'K': 2, 'Elementary': 3, 'Middle': 4, 'High': 5, 'Undefined': 0, 'NA': 0}).astype(int)
df['MDR_High_Grade'] = df['MDR_High_Grade'].replace({'PK': 1, 'K': 2, 'Elementary': 3, 'Middle': 4, 'High': 5, 'Undefined': 0, 'NA': 0}).astype(int)
df['SchoolGradeTypeLow'] = df['GroupGradeTypeHigh'].replace({'PK': 1, 'K': 2, 'Elementary': 3, 'Middle': 4, 'High': 5, 'Undefined': 0, 'NA': 0}).astype(int)
df['SchoolGradeTypeHigh'] = df['GroupGradeTypeLow'].replace({'PK': 1, 'K': 2, 'Elementary': 3, 'Middle': 4, 'High': 5, 'Undefined': 0, 'NA': 0}).astype(int)

C:\Users\franc\AppData\Local\Temp\ipykernel_6336\615223369.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['GroupGradeTypeHigh'] = df['GroupGradeTypeHigh'].replace({'PK': 1, 'K': 2, 'Elementary': 3, 'Middle': 4, 'High': 5, 'Undefined': 0, 'NA': 0}).astype(int)
C:\Users\franc\AppData\Local\Temp\ipykernel_6336\615223369.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['GroupGradeTypeLow'] = df['GroupGradeTypeLow'].replace({'PK': 1, 'K': 2, 'Elementary': 3, 'Middle': 4, 'High': 5, 'Undefined': 0, 'NA': 0}).astype(int)

In [1141]:
# FROM GRADE + TO GRADE 

# 1. Replace empty strings with NaN (only for From_Grade and To_Grade)
df[['From_Grade', 'To_Grade']] = df[['From_Grade', 'To_Grade']].replace('', pd.NA)

# 2. Find the most frequent (From_Grade, To_Grade) combination per Group_State
mode_per_group = (
    df.dropna(subset=['From_Grade', 'To_Grade'])  # Consider only non-missing pairs
    .groupby('Group_State')[['From_Grade', 'To_Grade']]
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else pd.NA)
)

# Merge back to fill missing From_Grade and To_Grade
df = df.merge(mode_per_group, on='Group_State', how='left', suffixes=('', '_mode'))

# 3. Fill missing values:
# - If both From_Grade and To_Grade are missing, use the most frequent combination for the Group_State
df.loc[df['From_Grade'].isna() & df['To_Grade'].isna(), ['From_Grade', 'To_Grade']] = \
    df.loc[df['From_Grade'].isna() & df['To_Grade'].isna(), ['From_Grade_mode', 'To_Grade_mode']].values

# - If only To_Grade is missing (From_Grade is already filled), use the most frequent To_Grade for that From_Grade in that Group_State
most_frequent_to_grade = (
    df.dropna(subset=['From_Grade', 'To_Grade'])  # Consider only non-missing pairs
    .groupby(['Group_State', 'From_Grade'])['To_Grade']
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else pd.NA)
)

df['To_Grade'] = df.apply(
    lambda row: most_frequent_to_grade.get((row['Group_State'], row['From_Grade']), row['To_Grade'])
    if pd.isna(row['To_Grade']) else row['To_Grade'], axis=1
)

# Convert 'To_Grade' and 'From_Grade' to numeric
df['To_Grade'] = pd.to_numeric(df['To_Grade'], errors='coerce')
df['From_Grade'] = pd.to_numeric(df['From_Grade'], errors='coerce')

# Drop unnecessary columns
df.drop(columns=['From_Grade_mode', 'To_Grade_mode'], inplace=True)

In [1142]:
# Find rows where 'From_Grade' is null
missing_grades = df[df['From_Grade'].isna() & df['To_Grade'].isna()][['From_Grade','To_Grade','Group_State']]

# Display those rows
print(missing_grades)

      From_Grade  To_Grade Group_State
667          NaN       NaN          PR
2137         NaN       NaN          PR
3673         NaN       NaN     Bermuda

These rows are not filled because ther are no valid entries of From_Grade and To_Grade for PR and Bermuda. <br>
Since these are only 3 rows, we can remove them.

In [1143]:
# Remove the rows from the original DataFrame
df = df[~df.index.isin(missing_grades.index)]

In [1144]:
# MDR_LOW_GRADE, MDR HIGH

# 1. Replace 0 with NaN for MDR_Low_Grade and MDR_High_Grade (since 0 represents missing values)
df[['MDR_Low_Grade', 'MDR_High_Grade']] = df[['MDR_Low_Grade', 'MDR_High_Grade']].replace(0, pd.NA)

# 2. Find the most frequent (MDR_Low_Grade, MDR_High_Grade) combination per Group_State
mode_per_group_mdr = (
    df.dropna(subset=['MDR_Low_Grade', 'MDR_High_Grade'])  # Consider only non-missing pairs
    .groupby('Group_State')[['MDR_Low_Grade', 'MDR_High_Grade']]
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else pd.NA)
)

# Merge back to fill missing MDR_Low_Grade and MDR_High_Grade
df = df.merge(mode_per_group_mdr, on='Group_State', how='left', suffixes=('', '_mode'))

# 3. Fill missing values:
# - If both MDR_Low_Grade and MDR_High_Grade are missing, use the most frequent combination for the Group_State
df.loc[df['MDR_Low_Grade'].isna() & df['MDR_High_Grade'].isna(), ['MDR_Low_Grade', 'MDR_High_Grade']] = \
    df.loc[df['MDR_Low_Grade'].isna() & df['MDR_High_Grade'].isna(), ['MDR_Low_Grade_mode', 'MDR_High_Grade_mode']].values

# - If only MDR_High_Grade is missing (MDR_Low_Grade is already filled), use the most frequent MDR_High_Grade for that MDR_Low_Grade in that Group_State
most_frequent_mdr_high_grade = (
    df.dropna(subset=['MDR_Low_Grade', 'MDR_High_Grade'])  # Consider only non-missing pairs
    .groupby(['Group_State', 'MDR_Low_Grade'])['MDR_High_Grade']
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else pd.NA)
)

df['MDR_High_Grade'] = df.apply(
    lambda row: most_frequent_mdr_high_grade.get((row['Group_State'], row['MDR_Low_Grade']), row['MDR_High_Grade'])
    if pd.isna(row['MDR_High_Grade']) else row['MDR_High_Grade'], axis=1
)

# Drop unnecessary columns
df.drop(columns=['MDR_Low_Grade_mode', 'MDR_High_Grade_mode'], inplace=True)



# Filling MDR low/high grade
mean = df['MDR_Low_Grade'].mean() 
df['MDR_Low_Grade'].fillna(mean, inplace=True)
mean = df['MDR_High_Grade'].mean() 
df['MDR_High_Grade'].fillna(mean, inplace=True)

C:\Users\franc\AppData\Local\Temp\ipykernel_6336\2979723810.py:40: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['MDR_Low_Grade'].fillna(mean, inplace=True)
C:\Users\franc\AppData\Local\Temp\ipykernel_6336\2979723810.py:40: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['MDR_Low_Grade'].fillna(mean, inplace=True)
C:\Users\franc\AppData\Local\Temp\ipykernel_6336\2979723810.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['MDR_High_Grade'].fillna(mean, inplace=True)

## Dates

In [1145]:
df['Return_Date'] = pd.to_datetime(df['Return_Date'])
df['Early_RPL'] = pd.to_datetime(df['Early_RPL'])
df['Latest_RPL'] = pd.to_datetime(df['Latest_RPL'])
df['Initial_System_Date'] = pd.to_datetime(df['Initial_System_Date'])
df['Deposit_Date'] = pd.to_datetime(df['Deposit_Date'])

# DEPARTURE DATE
df['Departure_Date'] = pd.to_datetime(df['Departure_Date'])

### First and last meeting

In [1146]:
df['LastMeeting'] = pd.to_datetime(df['LastMeeting'])
df['FirstMeeting'] = pd.to_datetime(df['FirstMeeting'])

In [1147]:
df_filtered = df[df['LastMeeting'].notna()]

days_last_to_departure = (df_filtered['Departure_Date'] - df_filtered['LastMeeting']).dt.days
median_last_to_departure = days_last_to_departure.median()

print(f"Median days between LastMeeting and Departure_Date: {median_last_to_departure}")

days_first_to_last = (df_filtered['LastMeeting'] - df_filtered['FirstMeeting']).dt.days
median_first_to_last = days_first_to_last.median()

print(f"Median days between FirstMeeting and LastMeeting: {median_first_to_last}")

Median days between LastMeeting and Departure_Date: 232.0
Median days between FirstMeeting and LastMeeting: 4.0

In [1148]:
# Calculate LastMeeting for missing values by subtracting the median
df['LastMeeting'] = df.apply(
    lambda row: row['Departure_Date'] - pd.Timedelta(days=median_last_to_departure)
    if pd.isna(row['LastMeeting']) else row['LastMeeting'], axis=1
)

In [1149]:
# Calculate FirstMeeting for missing values by subtracting the median from LastMeeting
df['FirstMeeting'] = df.apply(
    lambda row: row['LastMeeting'] - pd.Timedelta(days=median_first_to_last)
    if pd.isna(row['FirstMeeting']) else row['FirstMeeting'], axis=1
)

### Initial_System_Date

In [1150]:
# Check if all Initial_System_Date values are before Departure_Date
are_all_before = (df['Initial_System_Date'] < df['Departure_Date']).all()

if are_all_before:
    print("✅ All Initial_System_Date entries are before Departure_Date.")
else:
    # Display rows where Initial_System_Date is not before Departure_Date
    invalid_rows = df[df['Initial_System_Date'] >= df['Departure_Date']]
    print("❌ Not all Initial_System_Date entries are before Departure_Date. Here are the invalid rows:")
    print(invalid_rows)

❌ Not all Initial_System_Date entries are before Departure_Date. Here are the invalid rows:
Empty DataFrame
Columns: [ID_FINANCE, Deposit_Date, Special_Pay, Tuition, FRP_Active, FRP_Cancelled, FRP_Take_up_percent_, EZ_Pay_Take_Up_Rate, School_Sponsor, SPR_Group_Revenue, FPP_to_PAX, Num_of_Non_FPP_PAX, ID_TRIP, ID_SALES, Program_Code, From_Grade, To_Grade, Group_State, Days, Travel_Type, Departure_Date, Return_Date, Early_RPL, Latest_RPL, Cancelled_Pax, Total_Discount_Pax, Initial_System_Date, SPR_Product_Type, FPP, Total_Pax, DepartureMonth, GroupGradeTypeLow, GroupGradeTypeHigh, GroupGradeType, MajorProgramCode, FPP_to_School_enrollment, Retained, ID_CRM, Poverty_Code, Region, CRM_Segment, School_Type, Parent_Meeting_Flag, MDR_Low_Grade, MDR_High_Grade, Total_School_Enrollment, Income_Level, SPR_New_Existing, NumberOfMeetingswithParents, FirstMeeting, LastMeeting, DifferenceTraveltoFirstMeeting, DifferenceTraveltoLastMeeting, SchoolGradeTypeLow, SchoolGradeTypeHigh, SchoolGradeType, SchoolSizeIndicator]
Index: []

[0 rows x 57 columns]

OK. No strange rows (the weird results is because od Nans in Initial_System_Date)

In [1151]:
# Filling Initial_System_Date

# Calculate the difference in days between Departure_Date and Initial_System_Date for available rows
df['Days_from_Initial_System_to_Departure'] = (df['Departure_Date'] - df['Initial_System_Date']).dt.days

# Compute the median of these distances
median_days = df['Days_from_Initial_System_to_Departure'].median()

# Fill missing Initial_System_Date by subtracting the median days from Departure_Date
df.loc[df['Initial_System_Date'].isna(), 'Initial_System_Date'] = df['Departure_Date'] - pd.to_timedelta(median_days, unit='D')

### Latest_RPL

In [1152]:
# Calculate the difference in days between Departure_Date and Latest_RPL for available rows
df['Days_from_Latest_RPL_to_Departure'] = (df['Departure_Date'] - df['Latest_RPL']).dt.days

# Compute the median of these distances
median_latest_rpl_days = df['Days_from_Latest_RPL_to_Departure'].median()

# Fill missing Latest_RPL by subtracting the median days from Departure_Date
df.loc[df['Latest_RPL'].isna(), 'Latest_RPL'] = df['Departure_Date'] - pd.to_timedelta(median_latest_rpl_days, unit='D')

### Early_RPL

In [1153]:
# Create a new column 'Has_Early_RPL' that is 1 if Early_RPL is present, 0 if missing
df['Has_Early_RPL'] = np.where(df['Early_RPL'].notna(), 1, 0)

In [1154]:
# Check the counts of 1s and 0s in 'Has_Early_RPL'
print(df['Has_Early_RPL'].value_counts())

Has_Early_RPL
1    2980
0    1165
Name: count, dtype: int64

In [1155]:
# Count unique values for 'Has_Early_RPL'
unique_counts = df['Has_Early_RPL'].value_counts()
total_rows = len(df)

# Display the counts and the total number of rows
print("Unique Value Counts for 'Has_Early_RPL':")
print(unique_counts)
print(f"\nTotal number of rows in the DataFrame: {total_rows}")

Unique Value Counts for 'Has_Early_RPL':
Has_Early_RPL
1    2980
0    1165
Name: count, dtype: int64

Total number of rows in the DataFrame: 4145

In [1156]:
# Count missing values using different methods
print("Missing values according to isnull().sum():", df['Early_RPL'].isnull().sum())
print("Zeros in 'Has_Early_RPL':", (df['Has_Early_RPL'] == 0).sum())

Missing values according to isnull().sum(): 1165
Zeros in 'Has_Early_RPL': 1165

## DifferenceTraveltoLastMeeting

In [1157]:
# Convert 'DifferenceTraveltoLastMeeting' to numeric (if not already)
df['DifferenceTraveltoLastMeeting'] = pd.to_numeric(df['DifferenceTraveltoLastMeeting'], errors='coerce')


# Fill missing values directly using the difference between 'Departure_Date' and 'LastMeeting'
df['DifferenceTraveltoLastMeeting'].fillna(
    (df['Departure_Date'] - df['LastMeeting']).dt.days,
    inplace=True
)

C:\Users\franc\AppData\Local\Temp\ipykernel_6336\2580355783.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DifferenceTraveltoLastMeeting'].fillna(

In [1158]:
# Check for missing values after conversion
missing_count = df['DifferenceTraveltoLastMeeting'].isna().sum()
print(f"Number of missing values: {missing_count}")

Number of missing values: 0

## DifferenceTraveltoFirstMeeting

In [1159]:
# Convert 'DifferenceTraveltoFirstMeeting' to numeric (if not already)
df['DifferenceTraveltoFirstMeeting'] = pd.to_numeric(df['DifferenceTraveltoFirstMeeting'], errors='coerce')

# Fill missing values directly using the difference between 'Departure_Date' and 'LastMeeting'
df['DifferenceTraveltoFirstMeeting'].fillna(
    (df['Departure_Date'] - df['FirstMeeting']).dt.days,
    inplace=True
)

C:\Users\franc\AppData\Local\Temp\ipykernel_6336\2317940870.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DifferenceTraveltoFirstMeeting'].fillna(

## Differences between dates

Let's create meaningful columns out of dates:

**Preparation & Planning Metrics (Updated):**

Days_from_Initial_System_to_Departure = Departure_Date - Initial_System_Date

Days_from_Latest_RPL_to_Departure = Departure_Date - Latest_RPL

Days_from_FirstMeeting_to_Departure = Departure_Date - FirstMeeting

Days_from_LastMeeting_to_Departure = Departure_Date - LastMeeting

Has_Early_RPL (Binary Indicator: 1 if present, 0 if missing)

**Duration Metrics:**

Days_from_Deposit_to_Departure = Departure_Date - Deposit_Date

Days_from_Departure_to_Return = Return_Date - Departure_Date

**Meeting Scheduling Metrics:**

Days_between_Meetings = LastMeeting - FirstMeeting

**Booking Process Metrics:**

Days_between_System_and_FirstMeeting = FirstMeeting - Initial_System_Date

Days_between_System_and_LastMeeting = LastMeeting - Initial_System_Date

In [1160]:
# Preparation & Planning Metrics
df['Days_from_Initial_System_to_Departure'] = (df['Departure_Date'] - df['Initial_System_Date']).dt.days
df['Days_from_Latest_RPL_to_Departure'] = (df['Departure_Date'] - df['Latest_RPL']).dt.days
df['Days_from_FirstMeeting_to_Departure'] = (df['Departure_Date'] - df['FirstMeeting']).dt.days
df['Days_from_LastMeeting_to_Departure'] = (df['Departure_Date'] - df['LastMeeting']).dt.days

# Duration Metrics
df['Days_from_Deposit_to_Departure'] = (df['Departure_Date'] - df['Deposit_Date']).dt.days
df['Days_from_Departure_to_Return'] = (df['Return_Date'] - df['Departure_Date']).dt.days

# Meeting Scheduling Metrics
df['Days_between_Meetings'] = (df['LastMeeting'] - df['FirstMeeting']).dt.days

# Booking Process Metrics
df['Days_between_System_and_FirstMeeting'] = (df['FirstMeeting'] - df['Initial_System_Date']).dt.days
df['Days_between_System_and_LastMeeting'] = (df['LastMeeting'] - df['Initial_System_Date']).dt.days

In [1161]:
# Check rows where Days_between_Meetings is 0
zero_days_rows = df[df['Days_between_Meetings'] == 0]

# Display these rows
print(zero_days_rows[['FirstMeeting', 'LastMeeting', 'Days_between_Meetings']])

     FirstMeeting LastMeeting  Days_between_Meetings
29     2018-09-28  2018-09-28                      0
60     2018-10-26  2018-10-26                      0
68     2018-09-16  2018-09-16                      0
75     2018-09-12  2018-09-12                      0
113    2018-09-27  2018-09-27                      0
...           ...         ...                    ...
3976   2018-09-27  2018-09-27                      0
3981   2018-08-30  2018-08-30                      0
3993   2018-10-24  2018-10-24                      0
4013   2018-09-18  2018-09-18                      0
4028   2018-08-24  2018-08-24                      0

[140 rows x 3 columns]

In [1162]:
# Select rows where 'Days_between_Meetings' is 0
zero_days_rows = df[df['Days_between_Meetings'] == 0]

# Check if all these rows have the same date for 'FirstMeeting' and 'LastMeeting'
matching_dates = (zero_days_rows['FirstMeeting'] == zero_days_rows['LastMeeting']).all()

# Display the result
if matching_dates:
    print("All rows with 'Days_between_Meetings' == 0 have the same date for 'FirstMeeting' and 'LastMeeting'.")
else:
    print("Not all rows with 'Days_between_Meetings' == 0 have the same date for 'FirstMeeting' and 'LastMeeting'.")

All rows with 'Days_between_Meetings' == 0 have the same date for 'FirstMeeting' and 'LastMeeting'.

In [1163]:
# Filter rows where 'Days_between_System_and_FirstMeeting' is 0
zero_days_rows = df[df['Days_between_System_and_FirstMeeting'] == 0]

# Display the relevant columns to inspect the issue
print(zero_days_rows[['FirstMeeting', 'Initial_System_Date', 'Days_between_System_and_FirstMeeting']])

     FirstMeeting Initial_System_Date  Days_between_System_and_FirstMeeting
507    2018-03-28          2018-03-28                                     0
608    2018-10-17          2018-10-17                                     0
842    2018-04-25          2018-04-25                                     0
1012   2018-11-21          2018-11-21                                     0
1802   2018-05-16          2018-05-16                                     0
2136   2018-09-04          2018-09-04                                     0
2325   2018-05-09          2018-05-09                                     0
2369   2018-09-28          2018-09-28                                     0
2513   2018-08-27          2018-08-27                                     0
2661   2018-10-06          2018-10-06                                     0
2701   2018-04-10          2018-04-10                                     0
3758   2018-08-18          2018-08-18                                     0

## NumberOfMeetingswithParents

In [1164]:
# Calculate the median, excluding zeros
median_meetings = df.loc[df['NumberOfMeetingswithParents'] != 0, 'NumberOfMeetingswithParents'].median()

print(f"Median of 'NumberOfMeetingswithParents' (excluding zeros): {median_meetings}")

df['NumberOfMeetingswithParents'] = df['NumberOfMeetingswithParents'].replace(0, median_meetings)

Median of 'NumberOfMeetingswithParents' (excluding zeros): 1.0

In [1165]:
# Check for missing values after conversion
missing_count = df['DifferenceTraveltoFirstMeeting'].isna().sum()
print(f"Number of missing values: {missing_count}")

Number of missing values: 0

## Total_School_Enrollment

In [1166]:
# Calculate the median of 'Total_School_Enrollment', excluding 0s and NaNs
median_enrollment = df.loc[df['Total_School_Enrollment'] != 0, 'Total_School_Enrollment'].median()
# Replace 0s in 'Total_School_Enrollment' with the calculated median
df['Total_School_Enrollment'] = df['Total_School_Enrollment'].replace(0, median_enrollment)

## FPP_to_School_enrollment

In [1167]:
# Replace commas with dots for decimal representation
df['FPP_to_School_enrollment'] = df['FPP_to_School_enrollment'].str.replace(",", ".")

# Replace empty strings with NaN
df['FPP_to_School_enrollment'].replace('', np.nan, inplace=True)

# Convert the column to float
df['FPP_to_School_enrollment'] = df['FPP_to_School_enrollment'].astype(float)

# Fill NaN values with the mean of the column
mean = df['FPP_to_School_enrollment'].mean()
df['FPP_to_School_enrollment'].fillna(mean, inplace=True)

C:\Users\franc\AppData\Local\Temp\ipykernel_6336\3304634208.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FPP_to_School_enrollment'].replace('', np.nan, inplace=True)
C:\Users\franc\AppData\Local\Temp\ipykernel_6336\3304634208.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FPP_to_School_enrollment'].fillna(mean, inplace=True)

## Special_Pay

In [1168]:
df['Special_Pay'] = df['Special_Pay'].replace('0', 'NA')
df.drop(columns=['Special_Pay'], inplace=True)

## FRP_Take_up_percent_

In [1169]:
df['FRP_Take_up_percent_'] = df['FRP_Take_up_percent_'].str.replace(',', '.').astype(float)

In [1170]:
# Step 1: Calculate the mean of 'FRP_Take_up_percent_' excluding zeros
mean_value = df.loc[df['FRP_Take_up_percent_'] != 0, 'FRP_Take_up_percent_'].mean()
#print(f"Mean of 'FRP_Take_up_percent_' (excluding zeros): {mean_value}")

# Step 2: Replace zeros with the calculated mean
df['FRP_Take_up_percent_'] = df['FRP_Take_up_percent_'].replace(0, mean_value)

## EZ_Pay_Take_Up_Rate

In [1171]:
df['EZ_Pay_Take_Up_Rate'] = df['EZ_Pay_Take_Up_Rate'].str.replace(',', '.').astype(float)
median_value = df['EZ_Pay_Take_Up_Rate'].median()
# Replace values greater than 1 with the median
df.loc[df['EZ_Pay_Take_Up_Rate'] > 1, 'EZ_Pay_Take_Up_Rate'] = median_value

In [1172]:
# Step 1: Calculate the median of 'EZ_Pay_Take_Up_Rate' excluding zeros
median_value = df.loc[df['EZ_Pay_Take_Up_Rate'] != 0, 'EZ_Pay_Take_Up_Rate'].median()
#print(f"Median of 'EZ_Pay_Take_Up_Rate' (excluding zeros): {median_value}")

# Step 2: Replace zeros with the calculated median
df['EZ_Pay_Take_Up_Rate'] = df['EZ_Pay_Take_Up_Rate'].replace(0, median_value)

## FPP_to_PAX

In [1173]:
df['FPP_to_PAX'] = df['FPP_to_PAX'].astype(str).str.replace(',', '.').astype(float)

## Num_of_Non_FPP_PAX

In [1174]:
# 1. Group by FPP and find the most frequent Num_of_Non_FPP_PAX for each FPP
most_frequent_non_fpp_pax = (
    df[df['Num_of_Non_FPP_PAX'] != 0]  # Consider only rows where Num_of_Non_FPP_PAX is not 0
    .groupby('FPP')['Num_of_Non_FPP_PAX']
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else pd.NA)
)

# 2. Replace 0 values in Num_of_Non_FPP_PAX with the most frequent Num_of_Non_FPP_PAX for each FPP
df['Num_of_Non_FPP_PAX'] = df.apply(
    lambda row: most_frequent_non_fpp_pax.get(row['FPP'], row['Num_of_Non_FPP_PAX']) 
    if row['Num_of_Non_FPP_PAX'] == 0 else row['Num_of_Non_FPP_PAX'], axis=1
)

## School_Type

In [1175]:
school_type_mapping = {'PUBLIC': 'PUB', 'Private non-Christian': 'PNC', 'Catholic': 'CAT', 'CHD': 'CHD'}
df["School_Type"] = df["School_Type"].map(school_type_mapping) # Map so dummy columns have better name

## SchoolSizeIndicator

In [1176]:
school_size_scale = {'S': 0, 'S-M': 1, 'M-L': 2, 'L': 3}
df['SchoolSizeIndicator'] = df['SchoolSizeIndicator'].map(school_size_scale)

## Income_Level


Handling the '0' and 'Z' Classes in the Income_Level Variable

Objective
Replace the rows with values ⁠ '0' ⁠ and ⁠ 'Z' ⁠ in the ⁠ Income_Level ⁠ column by redistributing them according to the proportion of the valid classes (i.e., all classes except ⁠ '0' ⁠ and ⁠ 'Z' ⁠).

---

Process

1. Calculate Class Proportions
•⁠  ⁠Exclude rows where the ⁠ Income_Level ⁠ is ⁠ '0' ⁠ or ⁠ 'Z' ⁠.
•⁠  ⁠Calculate the proportion of each remaining class using the ⁠ .value_counts(normalize=True) ⁠ function.

2. Assign Rows with ⁠ '0' ⁠
•⁠  ⁠Count the total number of rows labeled as ⁠ '0' ⁠.
•⁠  ⁠Redistribute these rows to other classes according to the previously calculated proportions using ⁠ np.random.choice() ⁠.
•⁠  ⁠Assign the new labels to the rows with ⁠ '0' ⁠ in the ⁠ Income_Level ⁠ column.

3. Assign Rows with ⁠ 'Z' ⁠
•⁠  ⁠Repeat the same procedure as for ⁠ '0' ⁠.
•⁠  ⁠Count the total number of rows labeled as ⁠ 'Z' ⁠.
•⁠  ⁠Redistribute these rows using the same proportions calculated above with ⁠ np.random.choice() ⁠.
•⁠  ⁠Replace the values ⁠ 'Z' ⁠ with the newly assigned class

In [1177]:
# Replace specific 'P' categories with 'P'
df['Income_Level'] = df['Income_Level'].replace(['P4', 'P5', 'P3', 'P1'], 'P')

# Exclude rows where Income_Level is '0' or 'Z'
filtered_df = df[(df['Income_Level'] != '0') & (df['Income_Level'] != 'Z')]

# Calculate the total number of rows without '0' and 'Z'
total_without_0_z = len(filtered_df)

# Calculate the proportion of each class (excluding '0' and 'Z')
class_proportions = filtered_df['Income_Level'].value_counts(normalize=True)
#print(class_proportions)

# Count the number of rows with '0'
num_0_rows = df['Income_Level'].value_counts().get('0', 0)

# Generate new labels for the '0' rows based on calculated proportions
new_labels_for_0 = np.random.choice(
    class_proportions.index,       # The unique classes
    size=num_0_rows,               # Number of '0' rows to replace
    p=class_proportions.values     # Probability distribution
)

# Assign the new labels to the '0' rows
df.loc[df['Income_Level'] == '0', 'Income_Level'] = new_labels_for_0

income_level_scale = {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9, 'K': 10, 'L': 11, 'M': 12, 'N': 13, 'O': 14, 'P': 15, 'Q': 16}
df['Income_Level'] = df['Income_Level'].map(income_level_scale)

In [1178]:
# The variable still presents missing values: let's fill them with the median

# Calculate the median of Income_Level excluding NaN values
median_income_level = df['Income_Level'].median()
# Replace NaN values in 'Income_Level' with the calculated median
df['Income_Level'].fillna(median_income_level, inplace=True)

C:\Users\franc\AppData\Local\Temp\ipykernel_6336\168441807.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Income_Level'].fillna(median_income_level, inplace=True)

## Poverty Code

In [1179]:
# Encoding

# Replace all '0' values in 'Poverty_Code' with NaN
df['Poverty_Code'] = df['Poverty_Code'].replace('0', np.nan)

poverty_code_counts = df['Poverty_Code'].value_counts(dropna=False)  # Include NaN values if present
print(poverty_code_counts)

Poverty_Code
B      1656
NaN    1050
C       881
A       462
D        67
E        29
Name: count, dtype: int64

In [1180]:
# Define a dictionary mapping for Poverty_Code
poverty_code_mapping = {
    'A': 1,
    'B': 2,
    'C': 3,
    'D': 4,
    'E': 5
}

In [1181]:
# Map the values in 'Poverty_Code' using the defined dictionary
df['Poverty_Code'] = df['Poverty_Code'].map(poverty_code_mapping)

In [1182]:
# Display the counts of the mapped values
print(df['Poverty_Code'].value_counts(dropna=False))

Poverty_Code
2.0    1656
NaN    1050
3.0     881
1.0     462
4.0      67
5.0      29
Name: count, dtype: int64

In [1183]:
# Calculate the correlation between 'Income_Level' and 'Poverty_Code'
correlation = df[['Income_Level', 'Poverty_Code']].corr().iloc[0, 1]

# Display the correlation coefficient
print(f"Correlation between Income_Level and Poverty_Code: {correlation:.4f}")

Correlation between Income_Level and Poverty_Code: -0.5736

# Check missing values

## Empty strings

In [1184]:
empty_counts = (df == '').sum()

result = pd.DataFrame({'Empty Strings': empty_counts})
print(result)

                                      Empty Strings
ID_FINANCE                                        0
Deposit_Date                                      0
Tuition                                           0
FRP_Active                                        0
FRP_Cancelled                                     0
...                                             ...
Days_from_Deposit_to_Departure                    0
Days_from_Departure_to_Return                     0
Days_between_Meetings                             0
Days_between_System_and_FirstMeeting              0
Days_between_System_and_LastMeeting               0

[66 rows x 1 columns]

## Zeros (numeric columns)

In [1185]:
# Select numeric columns
numeric_cols = df.select_dtypes(include=['number'])

# Identify strictly binary columns (contain only 0 and 1)
binary_cols = [col for col in numeric_cols.columns if set(numeric_cols[col].dropna().unique()).issubset({0, 1})]

# Exclude strictly binary columns
non_binary_cols = numeric_cols.drop(columns=binary_cols)

# Count zeros in the remaining numeric columns
zero_counts = (non_binary_cols == 0).sum()

print(zero_counts)

Tuition                                    0
FRP_Active                               221
FRP_Cancelled                            822
FRP_Take_up_percent_                       0
EZ_Pay_Take_Up_Rate                        0
SPR_Group_Revenue                          0
FPP_to_PAX                                 0
Num_of_Non_FPP_PAX                         2
ID_TRIP                                    0
From_Grade                                 0
To_Grade                                   0
Days                                       0
Cancelled_Pax                            417
Total_Discount_Pax                        27
FPP                                        0
Total_Pax                                  0
GroupGradeTypeLow                        113
GroupGradeTypeHigh                       113
FPP_to_School_enrollment                   0
Poverty_Code                               0
MDR_Low_Grade                              0
MDR_High_Grade                             0
Total_School_Enrollment                    0
Income_Level                              37
NumberOfMeetingswithParents                0
DifferenceTraveltoFirstMeeting             0
DifferenceTraveltoLastMeeting              0
SchoolGradeTypeLow                       113
SchoolGradeTypeHigh                      113
SchoolSizeIndicator                      881
Days_from_Initial_System_to_Departure      0
Days_from_Latest_RPL_to_Departure          0
Days_from_FirstMeeting_to_Departure        0
Days_from_LastMeeting_to_Departure         0
Days_from_Deposit_to_Departure             0
Days_from_Departure_to_Return              0
Days_between_Meetings                    140
Days_between_System_and_FirstMeeting      12
Days_between_System_and_LastMeeting       13
dtype: int64

Drop rows where FPP = 0 (not possible)

In [1186]:
# Identify the indices of rows where 'FPP' is equal to 0
indices_to_drop = df[df['FPP'] == 0].index

# Drop those rows using their indices
df.drop(index=indices_to_drop, inplace=True)

Drop rows where Num_of_Non_FPP_PAX = 0 (not possible)

In [1187]:
# Identify the indices of rows where 'FPP' is equal to 0
indices_to_drop = df[df['Num_of_Non_FPP_PAX'] == 0].index

# Drop those rows using their indices
df.drop(index=indices_to_drop, inplace=True)

## Null Values

In [1188]:
# Ensure pandas displays all columns
pd.set_option('display.max_rows', None)

missing_values = df.isnull().sum()
print(missing_values)

# Reset the option after checking
pd.reset_option('display.max_rows')

ID_FINANCE                                  0
Deposit_Date                                0
Tuition                                     0
FRP_Active                                  0
FRP_Cancelled                               0
FRP_Take_up_percent_                        0
EZ_Pay_Take_Up_Rate                         0
School_Sponsor                              0
SPR_Group_Revenue                           0
FPP_to_PAX                                  0
Num_of_Non_FPP_PAX                          0
ID_TRIP                                     0
ID_SALES                                    0
Program_Code                                0
From_Grade                                  0
To_Grade                                    0
Group_State                                 0
Days                                        0
Travel_Type                                 0
Departure_Date                              0
Return_Date                                 0
Early_RPL                                1163
Latest_RPL                                  0
Cancelled_Pax                               0
Total_Discount_Pax                          0
Initial_System_Date                         0
SPR_Product_Type                            0
FPP                                         0
Total_Pax                                   0
DepartureMonth                              0
GroupGradeTypeLow                           0
GroupGradeTypeHigh                          0
GroupGradeType                              0
MajorProgramCode                            0
FPP_to_School_enrollment                    0
Retained                                    0
ID_CRM                                      0
Poverty_Code                             1048
Region                                      0
CRM_Segment                                 0
School_Type                                 0
Parent_Meeting_Flag                         0
MDR_Low_Grade                               0
MDR_High_Grade                              0
Total_School_Enrollment                     0
Income_Level                                0
SPR_New_Existing                            0
NumberOfMeetingswithParents                 0
FirstMeeting                                0
LastMeeting                                 0
DifferenceTraveltoFirstMeeting              0
DifferenceTraveltoLastMeeting               0
SchoolGradeTypeLow                          0
SchoolGradeTypeHigh                         0
SchoolGradeType                             0
SchoolSizeIndicator                       154
Days_from_Initial_System_to_Departure       0
Days_from_Latest_RPL_to_Departure           0
Has_Early_RPL                               0
Days_from_FirstMeeting_to_Departure         0
Days_from_LastMeeting_to_Departure          0
Days_from_Deposit_to_Departure              0
Days_from_Departure_to_Return               0
Days_between_Meetings                       0
Days_between_System_and_FirstMeeting        0
Days_between_System_and_LastMeeting         0
dtype: int64

# New Columns

In [1189]:
df['Cancellation_Rate'] = df['Cancelled_Pax'] / (df['Total_Pax'] + df['Cancelled_Pax'])
df['Revenue_per_PAX'] = df['SPR_Group_Revenue'] / df['Total_Pax']
df['Deposit_Ratio'] = df['Tuition'] / df['Total_Pax']
df['Insurance_Cancellation_Rate'] = df['FRP_Cancelled'] / df['FRP_Active']
median = df['Insurance_Cancellation_Rate'].median() 
# Replace missing values with the median - Preferred way
median = df['Insurance_Cancellation_Rate'].median()
df['Insurance_Cancellation_Rate'] = df['Insurance_Cancellation_Rate'].fillna(median)
df['Months_to_Departure'] = (df['Departure_Date'].dt.year - df['Deposit_Date'].dt.year) * 12 + \
                            (df['Departure_Date'].dt.month - df['Deposit_Date'].dt.month)

df['Past_Bookings'] = df.groupby(['Program_Code', 'Group_State'])['Initial_System_Date'].rank(method='dense', ascending=True) - 1 # Initlay System Date (3/2017 - 3/2019)
df['Initial_Year'] = df['Initial_System_Date'].dt.year
df['Initial_Season'] = df['Initial_System_Date'].dt.month % 12 // 3  # 0: Winter, 1: Spring, 2: Summer, 3: Autumn

df['Grade_Span'] = df['To_Grade'] - df['From_Grade']
df['Departure_Season'] = df['Departure_Date'].dt.quarter

In [1190]:
# Find rows where 'Insurance_Cancellation_Rate' is either inf or -inf
problematic_rows = df[np.isinf(df['Insurance_Cancellation_Rate'])]

# Display the problematic rows with relevant columns
print(problematic_rows[['Insurance_Cancellation_Rate', 'FRP_Cancelled', 'FRP_Active']])

      Insurance_Cancellation_Rate  FRP_Cancelled  FRP_Active
852                           inf              2           0
1242                          inf              1           0
1340                          inf              1           0
1583                          inf              2           0
2208                          inf              1           0
2486                          inf              1           0
2519                          inf              2           0
2528                          inf              2           0
2685                          inf              3           0
2825                          inf              1           0
2878                          inf              1           0
2943                          inf              4           0
2952                          inf              2           0
3026                          inf              2           0
3140                          inf              4           0
3603                          inf              1           0
3608                          inf              3           0
3612                          inf              1           0

In [1191]:
print(f"df shape: {df.shape}")

df shape: (4143, 76)

In [1192]:
# Drop these rows from the original DataFrame
df = df.drop(problematic_rows.index)

In [1193]:
print(f"df shape: {df.shape}")

df shape: (4125, 76)

# Columns to drop

In [1194]:
df = df.drop(columns=['CRM_Segment'])

Given that Poverty_Code has 1000 missing values out of 4000 and its high correlation with Income_Level, we decide to drop it.

In [1195]:
df = df.drop(columns=['Poverty_Code'])

In [1196]:
# DEPARTURE MONTH (ROTTA) E TOTAL DISCOUNT PAX (CORRELAZIONE 99 con NumOfNonFPP)
df = df.drop(columns=['DepartureMonth', 'Total_Discount_Pax'])

We decide to keep only numeric grades and drop their categorizations.

In [1197]:
# Drop useless columns

df = df.drop(columns=['GroupGradeTypeLow','GroupGradeTypeHigh','SchoolGradeTypeLow','SchoolGradeTypeHigh','SchoolSizeIndicator'])

In [1198]:
# ID_CRM AND ID_FINANCE
df = df.drop(columns=["ID_CRM", "ID_FINANCE"])

In [1199]:
# Remove SchoolGradeType 
df = df.drop(columns=["SchoolGradeType"])

In [1200]:
# Drop dates
columns_to_drop = ['Deposit_Date', 'Departure_Date', 'Return_Date', 'Early_RPL', 'Latest_RPL', 'Initial_System_Date', 'FirstMeeting', 'LastMeeting']
df.drop(columns=columns_to_drop, inplace=True)

# Check 0s after column removal

In [1201]:
# Select numeric columns
numeric_cols = df.select_dtypes(include=['number'])

# Identify strictly binary columns (contain only 0 and 1)
binary_cols = [col for col in numeric_cols.columns if set(numeric_cols[col].dropna().unique()).issubset({0, 1})]

# Exclude strictly binary columns
non_binary_cols = numeric_cols.drop(columns=binary_cols)

# Count zeros in the remaining numeric columns
zero_counts = (non_binary_cols == 0).sum()

print(zero_counts)

Tuition                                     0
FRP_Active                                201
FRP_Cancelled                             820
FRP_Take_up_percent_                        0
EZ_Pay_Take_Up_Rate                         0
SPR_Group_Revenue                           0
FPP_to_PAX                                  0
Num_of_Non_FPP_PAX                          0
ID_TRIP                                     0
From_Grade                                  0
To_Grade                                    0
Days                                        0
Cancelled_Pax                             417
FPP                                         0
Total_Pax                                   0
FPP_to_School_enrollment                    0
MDR_Low_Grade                               0
MDR_High_Grade                              0
Total_School_Enrollment                     0
Income_Level                               37
NumberOfMeetingswithParents                 0
DifferenceTraveltoFirstMeeting              0
DifferenceTraveltoLastMeeting               0
Days_from_Initial_System_to_Departure       0
Days_from_Latest_RPL_to_Departure           0
Days_from_FirstMeeting_to_Departure         0
Days_from_LastMeeting_to_Departure          0
Days_from_Deposit_to_Departure              0
Days_from_Departure_to_Return               0
Days_between_Meetings                     140
Days_between_System_and_FirstMeeting       12
Days_between_System_and_LastMeeting        12
Cancellation_Rate                         417
Revenue_per_PAX                             0
Deposit_Ratio                               0
Insurance_Cancellation_Rate               619
Months_to_Departure                         2
Past_Bookings                             285
Initial_Year                                0
Initial_Season                           1082
Grade_Span                               2483
Departure_Season                            0
dtype: int64

NB <br>
- **FRP_Active** There may be trips in which some students did not buy trip cancellation insurance -> 0 is an acceptable value. <br>
- **FRP_Cancelled** There may be trips in which students bought the insurance and nobody deleted it. <br>
- **Cancelled_Pax** It is possible that some trips did not have students that made deposits and then cancelled -> 0 is an acceptable value. <br>
- **Income_Level** Given the adopted encoding, 0 is an acceptable value. <br>
- **Days_between_Meetings** Some observations have FirstMeeting = LastMeeting (1 meeting in total) -> 0 is an acceptable value <br>
- **Days_between_System_and_FirstMeeting** Some observations have the same date for Initial_System_Date anf FirstMeeting -> 0 is an acceptable value <br>
- **Days_between_System_and_LastMeeting** what said above makes 0 an acceptable values here too. <br>

In [1202]:
display(df)

,Tuition,FRP_Active,FRP_Cancelled,FRP_Take_up_percent_,EZ_Pay_Take_Up_Rate,School_Sponsor,SPR_Group_Revenue,FPP_to_PAX,Num_of_Non_FPP_PAX,ID_TRIP,...,Cancellation_Rate,Revenue_per_PAX,Deposit_Ratio,Insurance_Cancellation_Rate,Months_to_Departure,Past_Bookings,Initial_Year,Initial_Season,Grade_Span,Departure_Season
0,397,1,1,0.020913,0.017856,1,447,0.967036,2,1389,...,0.096774,7.982143,7.089286,1.000000,6,40.0,2018,1,1.0,2
1,563,0,0,0.600876,0.217302,0,579,0.993127,1,3090,...,0.000000,13.159091,12.795455,0.181818,5,89.0,2018,2,0.0,2
2,617,0,0,0.600876,0.217302,0,529,0.973946,1,3639,...,0.000000,11.020833,12.854167,0.181818,6,92.0,2018,2,0.0,2
3,446,1,1,0.019032,0.019285,1,381,0.981972,2,4249,...,0.107143,7.620000,8.920000,1.000000,7,26.0,2018,1,1.0,2
4,582,15,11,0.597237,0.035036,1,596,0.963426,2,1021,...,0.500000,24.833333,24.250000,0.733333,6,65.0,2018,1,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4140,402,0,0,0.600876,0.217302,1,378,0.975006,1,886,...,0.081081,11.117647,11.823529,0.181818,6,9.0,2018,1,0.0,2
4141,670,0,0,0.600876,0.217302,0,734,0.910345,9,888,...,0.058824,9.175000,8.375000,0.181818,11,7.0,2018,1,0.0,2
4142,2151,0,0,0.600876,0.217302,0,2075,0.839255,2,899,...,0.285714,138.333333,143.400000,0.181818,11,10.0,2018,0,0.0,2
4143,414,0,0,0.600876,0.217302,1,418,0.966618,2,939,...,0.025000,10.717949,10.615385,0.181818,7,33.0,2018,1,0.0,2
4144,1729,0,0,0.600876,0.217302,1,1830,0.891704,5,959,...,0.018868,35.192308,33.250000,0.181818,5,115.0,2018,1,0.0,1

# Save dataframe

In [1203]:
df.to_csv('./data/df_clean.csv', index=False)